import {
  convertToModelMessages,
  streamText,
  type UIMessage,
} from "ai";

import {
  AI_MODEL,
  SYSTEM_PROMPT,
  AI_GENERATION_CONFIG,
} from "../../../lib/ai-config";

export async function POST(req: Request) {
  const {
    messages,
    code,
    audit,
  }: {
    messages: UIMessage[];
    code?: string;
    audit?: unknown;
  } = await req.json();

  const auditContext =
    code && audit
      ? `
The user is asking follow-up questions about a frontend code audit that was generated by this application.

ORIGINAL CODE:
${code}

AUDIT RESULT:
${JSON.stringify(audit, null, 2)}

Use this audit and code as the primary context for the conversation.

When the user asks things like:
- "Why did I get this score?"
- "How do I fix this issue?"
- "What should I improve first?"
- "Why is accessibility low?"

answer specifically using the audit above.

Do not claim that you cannot see the audit or that you need the user to repeat the score.
`
      : "";

  const result = streamText({
    model: AI_MODEL,

    system: `
${SYSTEM_PROMPT}

${auditContext}
    `,

    messages: await convertToModelMessages(messages),

    ...AI_GENERATION_CONFIG,
  });

  return result.toUIMessageStreamResponse();
}